### ISSUE TITLE
Ensure all Posted PDFs are Accessible

### ISSUE THREAD

**Issue by jayfo** [uwcse510/web-cse510-22au#17]
Ensure:
- Are not just scanned images
- Have a basic reading order

If a PDF needs replaced, then the Canvas link will also change.

More context via email.

Check all the PDFs that are already in Canvas.  When I add new PDFs to Canvas, I'll also indicate those need checked.

**Comment by lelkin** [comment]
**High Water Pants in research through design is NOT accessible.**

Designing with Children links said unauthorized. I’m assuming the links are still old even though they’re live on the website.

All other currently posted PDFs are accessible.
