### ISSUE TITLE
Create Canvas Discussion Threads

### ISSUE THREAD

**Issue by jayfo** [uwcse510/web-cse510-22au#28]
All of the discussion topics are now posted and finalized. Need to create discussion threads.

- [ ] 11/1
- [ ] 11/3
- [ ] 11/15
- [ ] 11/17
- [ ] 11/22
- [ ] 12/6
- [ ] 12/8

Priority is obviously 11/1 and 11/3.

**Comment by lelkin** [comment]
Done
